# Generated by Django 4.2.7 on 2023-12-01 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_auto_20191202_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Deadline'),
            preserve_default=False,
        ),
    ]
